VLOG=C:\questasim64_10.6c\win64\vlog
VSIM=C:\questasim64_10.6c\win64\vsim
VCOVER=C:\questasim64_10.6c\win64\vcover
VOPT=C:\questasim64_10.6c\win64\vopt


QUESTA_SIM_PATH  = 'C:\questasim64_10.6c'
compile:        
	$(VLOG) C:/questasim64_10.6c/uvm-1.1c/sequence_library/rtl/top.sv -l compile.log 

